import {Channel, AppSettings} from '../types';

export const DEMO_CHANNELS: Channel[] = [
  {
    id: 'ch1',
    name: 'BBC One HD',
    url: 'demo://bbc-one',
    logo: 'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'News',
    favorite: false,
  },
  {
    id: 'ch2',
    name: 'CNN International',
    url: 'demo://cnn',
    logo: 'https://images.pexels.com/photos/3944091/pexels-photo-3944091.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'News',
    favorite: false,
  },
  {
    id: 'ch3',
    name: 'Discovery Channel',
    url: 'demo://discovery',
    logo: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Documentary',
    favorite: false,
  },
  {
    id: 'ch4',
    name: 'ESPN Sports',
    url: 'demo://espn',
    logo: 'https://images.pexels.com/photos/274422/pexels-photo-274422.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Sports',
    favorite: false,
  },
  {
    id: 'ch5',
    name: 'National Geographic',
    url: 'demo://natgeo',
    logo: 'https://images.pexels.com/photos/1624496/pexels-photo-1624496.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Documentary',
    favorite: false,
  },
  {
    id: 'ch6',
    name: 'MTV Music',
    url: 'demo://mtv',
    logo: 'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Music',
    favorite: false,
  },
  {
    id: 'ch7',
    name: 'Comedy Central',
    url: 'demo://comedy',
    logo: 'https://images.pexels.com/photos/1115816/pexels-photo-1115816.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Entertainment',
    favorite: false,
  },
  {
    id: 'ch8',
    name: 'Food Network',
    url: 'demo://food',
    logo: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Lifestyle',
    favorite: false,
  },
  {
    id: 'ch9',
    name: 'History Channel',
    url: 'demo://history',
    logo: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Documentary',
    favorite: false,
  },
  {
    id: 'ch10',
    name: 'Cartoon Network',
    url: 'demo://cartoon',
    logo: 'https://images.pexels.com/photos/1148998/pexels-photo-1148998.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Kids',
    favorite: false,
  },
];

export const DEFAULT_SETTINGS: AppSettings = {
  theme: 'dark',
  autoplay: true,
  volume: 80,
  quality: 'auto',
  showEPG: true,
  gridSize: 'medium',
  layoutMode: 'grid',
  language: 'en',
  player: 'default',
  streamFormat: 'hls',
  timeFormat: '12h',
  deviceType: 'tv',
  subtitles: {
    enabled: false,
    language: 'en',
    fontSize: 'medium',
    color: '#ffffff',
    backgroundColor: '#000000',
    position: 'bottom',
  },
  parentalControl: {
    enabled: false,
    pin: '0000',
    lockedCategories: [],
  },
  hiddenCategories: {
    live: [],
    vod: [],
    series: [],
  },
  automaticUpdate: {
    enabled: false,
    frequency: 'daily',
    lastUpdate: null,
  },
};

export const COLORS = {
  primary: '#EAB308',
  secondary: '#1F2937',
  background: '#000000',
  surface: '#1F2937',
  text: '#FFFFFF',
  textSecondary: '#9CA3AF',
  error: '#EF4444',
  success: '#10B981',
  warning: '#F59E0B',
};